service: blog

provider:
  name: aws
  region: ap-southeast-2
  state: prod

package:
  individually: true

functions:
  rust:
    runtime: provided.al2
    handler: hello.handler
    package:
      artifact: deploy.zip